jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3307/springboot_test
  username: root
  password: 123456

# 激活配置文件，需要指定其他配置文件名称
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/springboot_test
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

# 修改tomcat端口
server:
  port: 80

# 日志记录级别
logging:
  level:
    com.itheima: debug
    org.springframework: info

mybatis:
  # 实体类别名包路径
  type-aliases-package: com.itheima.pojo
  # 映射文件路径
  # mapper-locations: classpath:mappers/*.xml
  # 日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl